version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: host
    volumes:
      - /opt/imagetrends-logs/db:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=imagetrends
      - MYSQL_ROOT_HOST=127.0.0.1
      - MYSQL_DATABASE=imagetrends
      - MYSQL_USER=imagetrends
      - MYSQL_PASSWORD=imagetrends
    security_opt:
      - seccomp:unconfined

  ui:
    image: imagetrends:latest
    restart: always
    network_mode: host
    volumes:
      - /opt/imagetrends-logs/ui:/app/log
    depends_on:
      - db
    environment:
      DB_NAME: imagetrends
      DB_USER: imagetrends
      DB_PASS: imagetrends
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      RAILS_ENV: production
      RAILS_MASTER_KEY: cdf56d76316a62b4532137d4fbb7b1b5
      WAIT_HOSTS: 127.0.0.1:3306