Description: >
    This template deploys an S3 bucket for hosting uploaded images.

Resources:

  ImageUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
    DeletionPolicy: Delete
  
  ImageUploadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ImageUploadBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ImageUploadBucket
                - /*
      Bucket: !Ref ImageUploadBucket

Outputs:

    ImageUploadBucket:
        Description: S3 Bucket where images are uploaded to.
        Value: !Ref ImageUploadBucket
