default: &default
  adapter: sqlite3
  pool: 5
  timeout: 10000

development:
  <<: *default
  database: db/development.sqlite3
  pool: 20
  timeout: 10000
  
test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: 200
  timeout: 10000
  settings:
    sql_mode: traditional
